<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="datagrid.aspx.cs" Inherits="WebApplication4.datagrid1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>DATA Mahasiswa</title>
  
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <br/><h1>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; DATA MAHASISWA UNIVERSITAS GUNADARMA</h1><br />
            <br/>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="NPM" DataSourceID="SqlDataSource2" Height="16px" Width="605px" PageSize="5" AllowPaging="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" CellPadding="4" ForeColor="#333333" GridLines="None" EnableSortingAndPagingCallbacks="True" AllowSorting="True" AutoGenerateDeleteButton="True" HorizontalAlign="Center">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:CommandField ShowEditButton="True" />
                    <asp:BoundField DataField="NPM" HeaderText="NPM" ReadOnly="True" SortExpression="NPM" />
                    <asp:BoundField DataField="Nama" HeaderText="Nama" SortExpression="Nama" />
                    <asp:BoundField DataField="Kelas" HeaderText="Kelas" SortExpression="Kelas" />
                    <asp:BoundField DataField="Jurusan" HeaderText="Jurusan" SortExpression="Jurusan" />
                    <asp:BoundField DataField="Fakultas" HeaderText="Fakultas" SortExpression="Fakultas" />
                </Columns>
                    
                <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                <SortedAscendingCellStyle BackColor="#FDF5AC" />
                <SortedAscendingHeaderStyle BackColor="#4D0000" />
                <SortedDescendingCellStyle BackColor="#FCF6C0" />
                <SortedDescendingHeaderStyle BackColor="#820000" />
                    
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:Database1 %>" SelectCommand="SELECT * FROM [Table]" OnSelecting="SqlDataSource2_Selecting" DeleteCommand="DELETE FROM [Table] WHERE [NPM] = @NPM" InsertCommand="INSERT INTO [Table] ([NPM], [Nama], [Kelas], [Jurusan], [Fakultas]) VALUES (@NPM, @Nama, @Kelas, @Jurusan, @Fakultas)" UpdateCommand="UPDATE [Table] SET [Nama] = @Nama, [Kelas] = @Kelas, [Jurusan] = @Jurusan, [Fakultas] = @Fakultas WHERE [NPM] = @NPM">
                <DeleteParameters>
                    <asp:Parameter Name="NPM" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="NPM" Type="Int32" />
                    <asp:Parameter Name="Nama" Type="String" />
                    <asp:Parameter Name="Kelas" Type="String" />
                    <asp:Parameter Name="Jurusan" Type="String" />
                    <asp:Parameter Name="Fakultas" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Nama" Type="String" />
                    <asp:Parameter Name="Kelas" Type="String" />
                    <asp:Parameter Name="Jurusan" Type="String" />
                    <asp:Parameter Name="Fakultas" Type="String" />
                    <asp:Parameter Name="NPM" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <br />
            <br />
        </div>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <asp:Label ID="Label1" runat="server" Text="Nama"></asp:Label>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;<asp:TextBox ID="TextBox1" runat="server" Width="262px" Height="16px"></asp:TextBox>
        <br />
        <br />
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <asp:Label ID="Label2" runat="server" Text="Kelas"></asp:Label>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;
        <asp:TextBox ID="TextBox2" runat="server" Width="262px" Height="16px"></asp:TextBox>
                <br />
                <br />
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp;<asp:Label ID="Label3" runat="server" Text="NPM"></asp:Label>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="TextBox3" runat="server" Width="262px" Height="16px"></asp:TextBox>
        <br />
        <br />
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;<asp:Label ID="Label4" runat="server" Text="Jurusan"></asp:Label>
        &nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp;&nbsp;
        <asp:TextBox ID="TextBox4" runat="server" Width="262px" Height="16px"></asp:TextBox>
        <br />
        <br />
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<asp:Label ID="Label5" runat="server" Text="Fakultas"></asp:Label>
        &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="TextBox5" runat="server" Width="262px" Height="16px"></asp:TextBox>
        <br />
        <br />
        <br />
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; <asp:Button ID="Button1" runat="server" Text="Simpan" OnClick="Button1_Click" />
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;
        &nbsp<asp:Button ID="Button2" runat="server" Text="Reset" Height="23px" OnClick="Button2_Click" Width="68px" />
        <br />

    </form>
</body>
</html>
